/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package copiadb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Inicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            try {
                String db_viejo = "mca_novedades";
                String db_nuevo = "mca_novedades_nuevo";
                String host = "localhost"; // host en el servidor del cliente
//                String host = "190.104.167.162"; // Host 4k

                Class.forName("org.postgresql.Driver");
                Connection conexion_viejo = DriverManager.getConnection("jdbc:postgresql://" + host + ":5432/" + db_viejo + "", "postgres", "postgres");
                Connection conexion_nuevo = DriverManager.getConnection("jdbc:postgresql://" + host + ":5432/" + db_nuevo + "", "postgres", "postgres");

                try {
                    int id = 0;
                    int c = 0;

                    Statement st1 = conexion_viejo.createStatement();
                    Statement st2 = conexion_viejo.createStatement();
                    ResultSet result2 = st2.executeQuery("SELECT * FROM productos");
                    while (result2.next()) {
                        id = result2.getInt(1) + 1;
                        PreparedStatement stUpdateProducto = conexion_nuevo.prepareStatement(""
                                + "INSERT INTO productos VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                        stUpdateProducto.setInt(1, result2.getInt(1));
                        stUpdateProducto.setInt(2, 1);
                        stUpdateProducto.setString(3, result2.getString(3));
                        stUpdateProducto.setString(4, result2.getString(4));
                        stUpdateProducto.setInt(5, result2.getInt(5));
                        stUpdateProducto.setInt(6, result2.getInt(6));
                        stUpdateProducto.setInt(7, result2.getInt(7));
                        stUpdateProducto.setInt(8, result2.getInt(8));
                        stUpdateProducto.setInt(9, result2.getInt(9));
                        stUpdateProducto.setString(10, result2.getString(10));
                        stUpdateProducto.setString(11, result2.getString(11));
                        stUpdateProducto.setString(12, result2.getString(12));
                        stUpdateProducto.setInt(13, 1);
                        stUpdateProducto.setString(14, result2.getString(14));
                        stUpdateProducto.setString(15, result2.getString(15));
                        stUpdateProducto.setInt(16, result2.getInt(16));
                        stUpdateProducto.setInt(17, 1 );
                        stUpdateProducto.setDate(18, null );
                        stUpdateProducto.setInt(19, 0);
                        stUpdateProducto.executeUpdate();
                        c++;
                    }
                    
                       PreparedStatement Update2 = conexion_nuevo.prepareStatement(""
                                  + "UPDATE productos SET stock = '0'");
            Update2.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "registros: " + c);

                } catch (SQLException ex) {
                    System.err.println(ex);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al iniciar la conexion con la base de datos.");
                System.exit(-1);
            }

        } catch (ClassNotFoundException ex) {

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
